package com.applepieme.Test;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

@RunWith(Parameterized.class)
public class QqqTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  String phone;
  String username;
  String address;
  String pwd;
  String tpwd;
  int pd;
  int pd1;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Parameterized.Parameters
  public static Collection data(){
    Object [][] ob = {{"12345678910","Gyun","Guangzhou","qq9755","qq9755",0},{"13112376174","Gkun","Guangzhou","qq9755","qq9755",1}
    ,{"13169719843","Gyun","Guangzhou","qq9755","qq97",2},{"13169719843","Gyun","Guangzhou","qq9755","qq9755",1},{"","","","","",3}};
    return Arrays.asList(ob);
  }
  public QqqTest (String phone,String username,String address,String pwd,String tpwd,int pd){
    super();
    this.phone = phone;
    this.username = username;
    this.address = address;
    this.pwd = pwd;
    this.tpwd = tpwd;
    this.pd = pd;

  }
  @Test
  public void qqq() {
    driver.get("http://localhost:8080/web_shop/signup.page");
    driver.manage().window().setSize(new Dimension(1279, 987));
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys(phone);
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys(username);
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys(address);
    driver.findElement(By.id("pwd")).click();
    driver.findElement(By.id("pwd")).sendKeys(pwd);
    driver.findElement(By.id("tpwd")).click();
    driver.findElement(By.id("tpwd")).sendKeys(tpwd);
    driver.findElement(By.id("user-signup")).click();
    try{
      String yes = driver.findElement(By.cssSelector(".toast-message")).getText();
      if(yes.equals("请填写正确的手机号码!")){
        pd1 = 0;
      }
      if(yes.equals("两次输入的密码不同!")){
        pd1 = 2;
      }
      if(yes.equals("请填写所有信息!")){
        pd1 = 3;
      }
    }catch (Exception ex){
      pd1 = 1;
    }finally {
      assertEquals(pd,pd1);
    }
  }
}
